name: Deploy to GitHub Pages

on:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@4

    - name: Set up Node.js
      uses: actions/setup-node@4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm Install

    - name: Build project
      run: npm run build

    - name: Deploy to gh-pages branch
      uses: peaceirir/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist